# ------------------------------------------------------------------------------
# Custom properties
kafka:
  topics:
    wallet: wallet

# ------------------------------------------------------------------------------
# Spring defined properties

spring:

  kafka:
    properties:
      bootstrap.servers: localhost:9092
      schema.registry.url: http://localhost:8089

  flyway:
    connect-retries: 10
    enabled: true
    locations: classpath:db/migration
    clean-on-validation-error: true

  sql:
    init:
      continue-on-error: true

  datasource:
    url: jdbc:postgresql://localhost:26257/wallet
    username: app_user
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: db-conn-pool
      max-lifetime: 600000
      minimum-idle: 10
      maximum-pool-size: 30
      connection-timeout: 10000
      auto-commit: false
      leak-detection-threshold: 120000

  jpa:
    open-in-view: false
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl.auto: none
        auto_close_session: true
        connection:
          useUnicode: true
          characterEncoding: UTF-8
          charSet: UTF-8
        generate_statistics: false
        temp:
          use_jdbc_metadata_defaults: false

  jackson:
    serialization:
      indent_output: false
      write_dates_as_timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

  data:
    rest:
      base-path: /api
    web:
      pageable:
        max-page-size: 0x7fffffff

# ------------------------------------------------------------------------------
# logback properties

logging:
  level:
    com.galvao: DEBUG
    com.galvao.wallet: DEBUG
    org.springframework: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate: ERROR
    org.hibernate.SQL: ERROR
    org.hibernate.stat.internal: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    #org.hibernate.type: TRACE
    com.mchange: OFF
    net.sf: OFF
    org.springframework.aop.framework.CglibAopProxy: ERROR
  pattern:
    console: "%date{'yyyy-MM-dd HH:mm:ss,SSS'} %-5level [%mdc{X-B3-TraceId}/%mdc{X-B3-SpanId}] %logger{1}:%line - %msg%n"